services:
  flask-app:
    image: ghcr.io/williamveith/mp3-download/mp3-downloader:latest
    container_name: app
    ports:
      - "0:5001"
    volumes:
      - ${HOME}/Downloads/Downloaded Music:/app/Downloaded Music
      - ${HOME}/Downloads/Updated Metadata:/app/Updated Metadata
    environment:
      FLASK_ENV: development
    restart: on-failure