services:
  flask-app:
    build: .
    image: mp3-downloader:latest
    container_name: app
    ports:
      - "0:5001"
    volumes:
      - ${HOME}/Downloads/Downloaded Music:/app/Downloaded Music
    environment:
      FLASK_ENV: development
    restart: on-failure
