name: run  # This is the name of the workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Clone specific repository
      - name: Clone specific repository
        run: |
          git clone git@github.com:williamveith/mp3-download.git
          cd mp3-download

      # Step 3: Checkout specific commit
      - name: Checkout specific commit
        run: |
          cd mp3-download
          git checkout ccbf2ab4  # Replace with your specific commit hash or branch

      # Step 4: Docker Compose up
      - name: Docker Compose up
        run: |
          cd mp3-download
          docker-compose up --build -d
