name: run

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

permissions:
  packages: write  # Grant GITHUB_TOKEN permission to push to the container registry

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platforms: [linux/amd64, linux/arm64]  # Define the platforms

    steps:
      # Step 1: Set up SSH agent with the private key from secrets
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 2: Checkout the repository using SSH and fetch full history
      - name: Checkout repository using SSH
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          fetch-depth: 0  # Fetch the full commit history

      # Step 3: Checkout specific commit by full hash
      - name: Checkout specific commit
        run: |
          git checkout d5c760f36cf5ceeb13f691c2d3d4afea2b3df755

      # Step 4: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Step 6: Build and push multi-architecture Docker images using Docker Buildx
      - name: Build and push multi-arch images with Docker Buildx
        run: |
          docker buildx create --use  # Create and switch to Buildx
          docker buildx build \
            --platform ${{ matrix.platforms }} \
            --push \
            --tag ghcr.io/williamveith/mp3-download/mp3-downloader:latest .

          # Add Docker labels
          docker buildx imagetools annotate \
            ghcr.io/williamveith/mp3-download/mp3-downloader:latest \
            --annotation org.opencontainers.image.source=https://github.com/williamveith/mp3-download \
            --annotation org.opencontainers.image.description="Multi-arch mp3 downloader container image" \
            --annotation org.opencontainers.image.licenses=MIT
