name: run

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

permissions:
    packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Set up SSH agent with the private key from secrets
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Your SSH private key stored in GitHub Secrets

      # Step 2: Checkout the repository using SSH and fetch full history
      - name: Checkout repository using SSH
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          fetch-depth: 0  # Fetch the full commit history

      # Step 3: Checkout specific commit by full hash
      - name: Checkout specific commit
        run: |
          git checkout d5c760f36cf5ceeb13f691c2d3d4afea2b3df755

      # Step 4: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Step 5: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Step 6: Build and tag the Docker image
      - name: Build and tag Docker image
        run: |
          docker-compose build
          docker tag mp3-downloader:latest ghcr.io/${{ github.repository }}/mp3-downloader:latest

      # Step 7: Push the Docker image to GitHub Container Registry
      - name: Push to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ github.repository }}/mp3-downloader:latest
