name: run  # This is the name of the workflow

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up SSH agent with the private key from secrets
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: Clone the specific repository using SSH
      - name: Clone specific repository
        run: |
          git clone git@github.com:williamveith/mp3-download.git
          cd mp3-download

      # Step 4: Checkout specific commit
      - name: Checkout specific commit
        run: |
          git checkout 66a575432d6c7ac9b33d31750b285fd2d0bc71a4

      # Step 5: Docker Compose up
      - name: Docker Compose up
        run: |
          docker-compose up --build -d
